/*
 * This file is automatically generated by the IRL Image Creator.
 *
 * @par COPYRIGHT NOTICE:
 * Copyright (c) 2025, Marijn van Stee, all rights reserved.
 *
 */

#ifndef FS_VERSION_H_
#define FS_VERSION_H_

#ifdef __cplusplus
extern "C" {
#endif

#define FS_IMAGE_FILE_VERSION_MAJOR  2u
#define FS_IMAGE_FILE_VERSION_MINOR  1u
#define FS_IMAGE_FILE_VERSION_PATCH  0u
#define FS_IMAGE_FILE_VERSION_REVISION  1u

#define FS_IMAGE_FILE_NAME "demo_3_pixeldata_2_1_0_1.bin"

#ifdef __cplusplus
}
#endif /*__cplusplus*/

#endif /*FS_VERSION_H_*/
