#ifndef VIEWS_SETTINGS_DATETIME_SETTINGS_VIEW_H_
#define VIEWS_SETTINGS_DATETIME_SETTINGS_VIEW_H_

void datetime_settings_view_navigateTo(void);

#endif /* VIEWS_SETTINGS_DATETIME_SETTINGS_VIEW_H_ */
