#ifndef VIEWS_SETTINGS_LANGUAGE_SETTINGS_VIEW_H_
#define VIEWS_SETTINGS_LANGUAGE_SETTINGS_VIEW_H_

void language_settings_view_navigateTo(void);

#endif /* VIEWS_SETTINGS_LANGUAGE_SETTINGS_VIEW_H_ */
