/*
 * This file is automatically generated by the IRL Image Creator.
 *
 * @par COPYRIGHT NOTICE:
 * Copyright (c) 2025, Marijn van Stee, all rights reserved.
 *
 */

#ifndef FS_FONT_SEARCH_H_
#define FS_FONT_SEARCH_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>

#ifndef FS_PIXEL_DATA_CRC
#define FS_PIXEL_DATA_CRC 186606574u
#endif

#define FS_FONTS 10
#define FS_CHAR_INFOS_IN_FONT 95
#define FS_BYTES_PER_PIXEL 2
#define FS_FONT_DATA_LOCATION 0

typedef enum
{
    FONT_KEY_TEXT_DARK_TEXT_ACCENT_BLUE = 0,
    FONT_KEY_TEXT_DARK_TEXT_ACCENT_RED = 1,
    FONT_KEY_TEXT_DARK = 2,
    FONT_KEY_TEXT_LIGHT_TEXT_ACCENT_BLUE = 3,
    FONT_KEY_TEXT_LIGHT_TEXT_ACCENT_RED = 4,
    FONT_KEY_TEXT_LIGHT = 5,
    FONT_KEY_TITLE_HEADER_DARK = 6,
    FONT_KEY_TITLE_HEADER_LIGHT = 7,
    FONT_KEY_TITLE_SMALL_HEADER_DARK = 8,
    FONT_KEY_TITLE_SMALL_HEADER_LIGHT = 9,
} font_key_e;

typedef struct
{
    uint32_t dataOffset;    // Pixeldata starts at this byte offset
    uint8_t width;          // Width of bmp in pixels
    uint8_t height;         // Height of bmp in pixels
} fs_char_info_s;

bool fs_getCharInfo(const char c, const font_key_e font_key, fs_char_info_s *p_out_char_info, uint8_t *p_dataLocation);


#ifdef __cplusplus
}
#endif /*__cplusplus*/

#endif /*FS_FONT_SEARCH_H_*/
