#ifndef STYLE_GUI_STYLE_H_
#define STYLE_GUI_STYLE_H_

#define STYLE_DISPLAY_WIDTH 480
#define STYLE_DISPLAY_HEIGHT 320

#define STYLE_VIEW_X 0
#define STYLE_VIEW_Y 42
#define STYLE_VIEW_WIDTH (STYLE_DISPLAY_WIDTH)
#define STYLE_VIEW_HEIGHT 216

#define STYLE_HEADER_X 0
#define STYLE_HEADER_Y 0
#define STYLE_HEADER_WIDTH (STYLE_DISPLAY_WIDTH)
#define STYLE_HEADER_HEIGHT 40
#define STYLE_HEADER_SEPARATOR_HEIGHT 2
#define SYTLE_HEADER_SEPARATOR_Y (STYLE_HEADER_Y + STYLE_HEADER_HEIGHT)
#define STYLE_HEADER_ICON_WIDTH (STYLE_HEADER_HEIGHT)
#define STYLE_HEADER_ICON_HEIGHT (STYLE_HEADER_HEIGHT)

#define STYLE_FOOTER_X 0
#define STYLE_FOOTER_Y 260
#define STYLE_FOOTER_WIDTH (STYLE_DISPLAY_WIDTH)
#define STYLE_FOOTER_HEIGHT 60
#define STYLE_FOOTER_SEPARATOR_HEIGHT 2
#define STYLE_FOOTER_SEPARATOR_Y (STYLE_FOOTER_Y - STYLE_FOOTER_SEPARATOR_HEIGHT)


#endif /* STYLE_GUI_STYLE_H_ */
