/*
 * This file is automatically generated by the IRL Image Creator.
 *
 * @par COPYRIGHT NOTICE:
 * Copyright (c) 2025, Marijn van Stee, all rights reserved.
 *
 */

#ifndef FS_PIXELDATA_H_
#define FS_PIXELDATA_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

typedef struct
{
    uint32_t readIndex;
    uint32_t pixelsToRead;
    uint16_t noOfPixelsLeft;
    uint16_t colorPixelLeft;
    uint32_t foreColor;
    uint32_t backColor;
} fs_pixeldata_info_s;

void fs_read(uint16_t *p_buffer, uint32_t bufferLength, fs_pixeldata_info_s *p_pixelDataInfo);
void fs_transferPixels(fs_pixeldata_info_s *p_pixelDataInfo, void (*transferPixels)(const uint16_t color, const int32_t noOfpixels));


#ifdef __cplusplus
}
#endif /*__cplusplus*/

#endif /*FS_PIXELDATA_H_*/
