#ifndef STYLE_GUI_STYLE_H_
#define STYLE_GUI_STYLE_H_

#define STYLE_DISPLAY_WIDTH 320
#define STYLE_DISPLAY_HEIGHT 240

#define STYLE_HEADER_X 0
#define STYLE_HEADER_Y 0
#define STYLE_HEADER_WIDTH (STYLE_DISPLAY_WIDTH)
#define STYLE_HEADER_HEIGHT 40
#define STYLE_HEADER_SEPARATOR_HEIGHT 1
#define SYTLE_HEADER_SEPARATOR_Y (STYLE_HEADER_Y + STYLE_HEADER_HEIGHT - STYLE_HEADER_SEPARATOR_HEIGHT)
#define STYLE_HEADER_ICON_WIDTH (STYLE_HEADER_HEIGHT)
#define STYLE_HEADER_ICON_HEIGHT (STYLE_HEADER_HEIGHT)

#define STYLE_FOOTER_WIDTH (STYLE_DISPLAY_WIDTH)
#define STYLE_FOOTER_HEIGHT 40
#define STYLE_FOOTER_SEPARATOR_HEIGHT 1
#define STYLE_FOOTER_SEPARATOR_Y (STYLE_DISPLAY_HEIGHT - STYLE_FOOTER_HEIGHT)
#define STYLE_FOOTER_X 0
#define STYLE_FOOTER_Y (STYLE_FOOTER_SEPARATOR_Y)
#define STYLE_FOOTER_BUTTON_HEIGHT (STYLE_FOOTER_HEIGHT - STYLE_FOOTER_SEPARATOR_HEIGHT)
#define STYLE_FOOTER_BUTTON_WIDTH (STYLE_FOOTER_BUTTON_HEIGHT)
#define STYLE_FOOTER_BUTTON_X 0
#define STYLE_FOOTER_BUTTON_Y (STYLE_FOOTER_Y + STYLE_FOOTER_SEPARATOR_HEIGHT)

#define STYLE_VIEW_X 0
#define STYLE_VIEW_Y (STYLE_HEADER_Y + STYLE_HEADER_HEIGHT)
#define STYLE_VIEW_WIDTH (STYLE_DISPLAY_WIDTH)
#define STYLE_VIEW_HEIGHT (STYLE_DISPLAY_HEIGHT - STYLE_HEADER_HEIGHT - STYLE_FOOTER_HEIGHT)


#endif /* STYLE_GUI_STYLE_H_ */
