/*
 * This file is automatically generated by the IRL Image Creator.
 *
 * @par COPYRIGHT NOTICE:
 * Copyright (c) 2025, Marijn van Stee, all rights reserved.
 *
 */

#ifndef FS_FILE_SEARCH_H_
#define FS_FILE_SEARCH_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>

#ifndef FS_PIXEL_DATA_CRC
#define FS_PIXEL_DATA_CRC 4119475913u
#endif

#define FS_FILES 864
#define FS_DATA_LOCATION_0_COMPRESSION 0 /* Compression None */
#define FS_MAX_FILE_PROPERTIES 5U
#define FS_BYTES_PER_PIXEL 2

typedef struct
{
    uint32_t dataOffset;  /* Pixeldata starts at this byte offset */
    uint8_t properties;   /* Properties in use */
    uint16_t width;       /* Width of image in pixels */
    uint16_t height;      /* Height of image in pixels */
} fs_file_info_s;

typedef enum
{
    FILE_SEARCH_OK = 0,
    FILE_SEARCH_OUT_OF_BOUNDS = 1,
    FILE_SEARCH_PROPERTY_LENGTH = 2,
    FILE_SEARCH_PROPERTY_NOT_FOUND = 3,
    FILE_SEARCH_DUMMY_NO_DATA = 4,
    FILE_SEARCH_ERROR_READING_DATA = 5,
} file_search_result_e;

typedef enum
{
    FS_DATA_LOCATION_0 = 0,
} fs_data_location_e;

typedef enum
{
    NONE = 0,
    RLE = 1,
    RLE_ALPHA = 2,
} fs_compression_e;

typedef enum
{
    FILE_PROPERTY_THEME = 0,
    FILE_PROPERTY_ANIMATION = 1,
    FILE_PROPERTY_LANGUAGE = 2,
    FILE_PROPERTY_FOCUS = 3,
    FILE_PROPERTY_ACCENT_COLOR = 4,
} file_property_e;

typedef enum
{
    PROPERTY_THEME_VALUE_LIGHT = 0,
    PROPERTY_THEME_VALUE_DARK = 1,
} property_value_theme_e;

typedef enum
{
    PROPERTY_ANIMATION_VALUE_0 = 0,
    PROPERTY_ANIMATION_VALUE_1 = 1,
    PROPERTY_ANIMATION_VALUE_2 = 2,
    PROPERTY_ANIMATION_VALUE_3 = 3,
    PROPERTY_ANIMATION_VALUE_4 = 4,
    PROPERTY_ANIMATION_VALUE_5 = 5,
    PROPERTY_ANIMATION_VALUE_6 = 6,
    PROPERTY_ANIMATION_VALUE_7 = 7,
    PROPERTY_ANIMATION_VALUE_8 = 8,
    PROPERTY_ANIMATION_VALUE_9 = 9,
    PROPERTY_ANIMATION_VALUE_10 = 10,
    PROPERTY_ANIMATION_VALUE_11 = 11,
    PROPERTY_ANIMATION_VALUE_12 = 12,
    PROPERTY_ANIMATION_VALUE_13 = 13,
    PROPERTY_ANIMATION_VALUE_14 = 14,
    PROPERTY_ANIMATION_VALUE_15 = 15,
    PROPERTY_ANIMATION_VALUE_16 = 16,
    PROPERTY_ANIMATION_VALUE_17 = 17,
    PROPERTY_ANIMATION_VALUE_18 = 18,
    PROPERTY_ANIMATION_VALUE_19 = 19,
    PROPERTY_ANIMATION_VALUE_20 = 20,
    PROPERTY_ANIMATION_VALUE_21 = 21,
    PROPERTY_ANIMATION_VALUE_22 = 22,
    PROPERTY_ANIMATION_VALUE_23 = 23,
} property_value_animation_e;

typedef enum
{
    PROPERTY_LANGUAGE_VALUE_ENGLISH = 0,
    PROPERTY_LANGUAGE_VALUE_DUTCH = 1,
    PROPERTY_LANGUAGE_VALUE_GERMAN = 2,
    PROPERTY_LANGUAGE_VALUE_FRENCH = 3,
    PROPERTY_LANGUAGE_VALUE_SPANISH = 4,
    PROPERTY_LANGUAGE_VALUE_ITALIAN = 5,
    PROPERTY_LANGUAGE_VALUE_RUSSIAN = 6,
    PROPERTY_LANGUAGE_VALUE_CHINESE = 7,
    PROPERTY_LANGUAGE_VALUE_JAPANESE = 8,
    PROPERTY_LANGUAGE_VALUE_KOREAN = 9,
} property_value_language_e;

typedef enum
{
    PROPERTY_FOCUS_VALUE_FALSE = 0,
    PROPERTY_FOCUS_VALUE_TRUE = 1,
} property_value_focus_e;

typedef enum
{
    PROPERTY_ACCENT_COLOR_VALUE_RED = 0,
    PROPERTY_ACCENT_COLOR_VALUE_GREEN = 1,
    PROPERTY_ACCENT_COLOR_VALUE_BLUE = 2,
    PROPERTY_ACCENT_COLOR_VALUE_WHITE = 3,
} property_value_accent_color_e;


typedef enum
{
    FILE_KEY_NONE = 0,
    FILE_KEY_ANIMATION_IRL_LOGO = 1,                  /* B: Animation */
    FILE_KEY_BUTTON_FOOTER_BUTTON = 25,               /* A: Theme */
    FILE_KEY_BUTTON_NUMINPUT_MINUS = 27,              /* A: Theme */
    FILE_KEY_BUTTON_NUMINPUT_PLUS = 29,               /* A: Theme */
    FILE_KEY_BUTTON_PAGE_BACKGROUND = 31,             /* A: Theme */
    FILE_KEY_BUTTON_SLIDER = 33,                      /* A: Theme */
    FILE_KEY_ICON_BUTTON_AGENDA = 35,                 /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_ARROW_BACK = 43,             /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_BELL = 51,                   /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_BRIGHTNESS = 59,             /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_BRUSH = 67,                  /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_CANCEL = 75,                 /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_CHECKMARK_LARGE = 83,        /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_CLOCK = 91,                  /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_FOCUS = 99,                  /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_GEAR = 107,                  /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_GLOBAL = 115,                /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_INFO = 123,                  /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_KEYBOARD = 131,              /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_PALETTE = 139,               /* A: Theme E: Accent Color */
    FILE_KEY_ICON_BUTTON_SLIDERS = 147,               /* A: Theme E: Accent Color */
    FILE_KEY_ICON_HEADER_BELL = 155,                  /* A: Theme */
    FILE_KEY_ICON_HEADER_CLOCK = 157,                 /* A: Theme */
    FILE_KEY_ICON_HEADER_WIFI = 159,                  /* A: Theme */
    FILE_KEY_ICON_PANE_ARROW_DOWN = 161,              /* A: Theme */
    FILE_KEY_ICON_PANE_ARROW_UP = 163,                /* A: Theme */
    FILE_KEY_ICON_PANE_CHECKMARK = 165,               /* A: Theme */
    FILE_KEY_ICON_PANE_MINUS = 167,                   /* A: Theme */
    FILE_KEY_ICON_PANE_PLUS = 169,                    /* A: Theme */
    FILE_KEY_ICON_PANE_RADIO_BUTTON_CHECKED = 171,    /* A: Theme E: Accent Color */
    FILE_KEY_ICON_PANE_RADIO_BUTTON_UNCHECKED = 179,  /* A: Theme E: Accent Color */
    FILE_KEY_IRL_LOGO_128 = 187,
    FILE_KEY_IRL_LOGO_48 = 188,
    FILE_KEY_KEYBOARD_LC = 189,                       /* A: Theme */
    FILE_KEY_KEYBOARD_NUM = 191,                      /* A: Theme */
    FILE_KEY_KEYBOARD_TEXTBOX = 193,                  /* A: Theme */
    FILE_KEY_KEYBOARD_UC = 195,                       /* A: Theme */
    FILE_KEY_TEXT_ACCENT_COLOR = 197,                 /* A: Theme C: Language */
    FILE_KEY_TEXT_ALARM = 217,                        /* A: Theme C: Language */
    FILE_KEY_TEXT_BRIGHTNESS = 237,                   /* A: Theme C: Language */
    FILE_KEY_TEXT_COLORS = 257,                       /* A: Theme C: Language */
    FILE_KEY_TEXT_DATE = 277,                         /* A: Theme C: Language */
    FILE_KEY_TEXT_FOOTER_MCSGUI = 297,                /* A: Theme */
    FILE_KEY_TEXT_INFO = 299,                         /* A: Theme C: Language */
    FILE_KEY_TEXT_KEYBOARD = 319,                     /* A: Theme C: Language */
    FILE_KEY_TEXT_LANGUAGE = 339,                     /* A: Theme C: Language */
    FILE_KEY_TEXT_MEASUREMENT = 359,                  /* A: Theme C: Language */
    FILE_KEY_TEXT_PANE_ACCENT_COLOR = 379,            /* A: Theme C: Language */
    FILE_KEY_TEXT_PANE_ACTIVATE_ALARM = 399,          /* A: Theme C: Language */
    FILE_KEY_TEXT_PANE_CHINESE_SIM = 419,             /* A: Theme */
    FILE_KEY_TEXT_PANE_CURSOR_COLOR = 421,            /* A: Theme C: Language */
    FILE_KEY_TEXT_PANE_DEG_CEL = 441,                 /* A: Theme */
    FILE_KEY_TEXT_PANE_DEG_FAR = 443,                 /* A: Theme */
    FILE_KEY_TEXT_PANE_DUTCH = 445,                   /* A: Theme */
    FILE_KEY_TEXT_PANE_ENGLISH = 447,                 /* A: Theme */
    FILE_KEY_TEXT_PANE_FRENCH = 449,                  /* A: Theme */
    FILE_KEY_TEXT_PANE_GERMAN = 451,                  /* A: Theme */
    FILE_KEY_TEXT_PANE_INTERN_TEMP = 453,             /* A: Theme C: Language */
    FILE_KEY_TEXT_PANE_ITALIAN = 473,                 /* A: Theme */
    FILE_KEY_TEXT_PANE_JAPANESE = 475,                /* A: Theme */
    FILE_KEY_TEXT_PANE_KOREAN = 477,                  /* A: Theme */
    FILE_KEY_TEXT_PANE_RUSSIAN = 479,                 /* A: Theme */
    FILE_KEY_TEXT_PANE_SET_ALARM_IN = 481,            /* A: Theme C: Language */
    FILE_KEY_TEXT_PANE_SPANISH = 501,                 /* A: Theme */
    FILE_KEY_TEXT_PANE_THEME_DARK = 503,              /* A: Theme C: Language */
    FILE_KEY_TEXT_PANE_THEME_LIGHT = 523,             /* A: Theme C: Language */
    FILE_KEY_TEXT_PANE_TIME_MM = 543,                 /* A: Theme */
    FILE_KEY_TEXT_SETTINGS = 545,                     /* A: Theme C: Language */
    FILE_KEY_TEXT_SETUP = 565,                        /* A: Theme C: Language */
    FILE_KEY_TEXT_THEME = 585,                        /* A: Theme C: Language */
    FILE_KEY_TEXT_TIME = 605,                         /* A: Theme C: Language */
    FILE_KEY_TITLE_ALARM = 625,                       /* A: Theme C: Language */
    FILE_KEY_TITLE_BRIGHTNESS = 645,                  /* A: Theme C: Language */
    FILE_KEY_TITLE_COLORS = 665,                      /* A: Theme C: Language */
    FILE_KEY_TITLE_DATE = 685,                        /* A: Theme C: Language */
    FILE_KEY_TITLE_INFO = 705,                        /* A: Theme C: Language */
    FILE_KEY_TITLE_LANGUAGE = 725,                    /* A: Theme C: Language */
    FILE_KEY_TITLE_MAIN_MENU = 745,                   /* A: Theme C: Language */
    FILE_KEY_TITLE_MEASUREMENT = 765,                 /* A: Theme C: Language */
    FILE_KEY_TITLE_SETTINGS = 785,                    /* A: Theme C: Language */
    FILE_KEY_TITLE_SETUP = 805,                       /* A: Theme C: Language */
    FILE_KEY_TITLE_THEME = 825,                       /* A: Theme C: Language */
    FILE_KEY_TITLE_TIME = 845,                        /* A: Theme C: Language */
} file_key_e;

/**
* @brief  Search the file info according to the file-key
*         and copy the data to the fs_file_info_s struct.
* @param  file_key a value from the file_key_e enum
* @param  p_out_file_info Pointer to a fs_file_info_s structure
*         where the file info data is copied to.
* @retval file_search_result_e
*/
file_search_result_e fs_getFileInfo(
                            const file_key_e file_key,
                            const uint8_t *p_properties,
                            const uint8_t propertiesLength,
                            fs_file_info_s *p_out_file_info,
                            uint8_t *p_dataLocation);

fs_compression_e fs_getCompression(const fs_data_location_e dataLocation);


#ifdef __cplusplus
}
#endif /*__cplusplus*/

#endif /*FS_FILE_SEARCH_H_*/
