#ifndef STYLE_STYLE_H_
#define STYLE_STYLE_H_

#define STYLE_DISPLAY_WIDTH 480
#define STYLE_DISPLAY_HEIGHT 320

#define STYLE_CONTROL_BAR_WIDTH 40
#define STYLE_CONTROL_BAR_HEIGHT STYLE_DISPLAY_HEIGHT
#define STYLE_CONTROL_BAR_SEPARATOR_WIDTH 2
#define STYLE_CONTROL_BAR_WIDTH_INC_SEPARATOR (STYLE_CONTROL_BAR_WIDTH + STYLE_CONTROL_BAR_SEPARATOR_WIDTH)

#define STYLE_VIEW_X STYLE_CONTROL_BAR_WIDTH_INC_SEPARATOR
#define STYLE_VIEW_Y 0
#define STYLE_VIEW_WIDTH (STYLE_DISPLAY_WIDTH - STYLE_CONTROL_BAR_WIDTH_INC_SEPARATOR)
#define STYLE_VIEW_HEIGHT STYLE_DISPLAY_HEIGHT


#endif /* STYLE_STYLE_H_ */
