#ifndef STYLE_GUI_COLORS_H_
#define STYLE_GUI_COLORS_H_

#define COLOR_IRL_BLUE 0x2195F2

#define COLOR_BACKGROUND_DARK 0x2C2C2C
#define COLOR_SEPARATOR_DARK 0x383838
#define COLOR_HEADER_BACKGROUND_DARK (COLOR_BACKGROUND_DARK)
#define COLOR_FOOTER_BACKGROUND_DARK (COLOR_BACKGROUND_DARK)
#define COLOR_PANE_BACKGROUND_DARK (COLOR_BACKGROUND_DARK)
#define COLOR_PANE_BORDER_DARK (COLOR_BACKGROUND_DARK)
#define COLOR_BUTTON_BACKGROUND_DARK 0x454545
#define COLOR_KEYBOARD_BUTTON_BACKGROUND_DARK 0x4E4E4E
#define COLOR_COMPONENT_BACKGROUND_DARK (COLOR_BUTTON_BACKGROUND_DARK)
#define COLOR_COMPONENT_BORDER_DARK (COLOR_SEPARATOR_DARK)

#define COLOR_BACKGROUND_LIGHT 0xEEEEEE
#define COLOR_SEPARATOR_LIGHT 0x999999
#define COLOR_HEADER_BACKGROUND_LIGHT (COLOR_IRL_BLUE)
#define COLOR_FOOTER_BACKGROUND_LIGHT (COLOR_BACKGROUND_LIGHT)
#define COLOR_PANE_BACKGROUND_LIGHT 0xFFFFFF
#define COLOR_PANE_BORDER_LIGHT (COLOR_SEPARATOR_LIGHT)
#define COLOR_BUTTON_BACKGROUND_LIGHT 0xFFFFFF
#define COLOR_KEYBOARD_BUTTON_BACKGROUND_LIGHT 0xDCDCDC
#define COLOR_COMPONENT_BACKGROUND_LIGHT (COLOR_BACKGROUND_LIGHT)
#define COLOR_COMPONENT_BORDER_LIGHT 0xD9D9D9

#define COLOR_ACCENT_RED 0xE81123
#define COLOR_ACCENT_GREEN 0x107C10
#define COLOR_ACCENT_BLUE 0x0078d4
#define COLOR_ACCENT_WHITE 0xE5E5E5
#define COLOR_ACCENT_BLACK 0x000000

#endif /* STYLE_GUI_COLORS_H_ */
